### ISSUE TITLE
Enhancement: Add auto-open function to shared folders

### ISSUE THREAD

**Issue by mchkzk** [flexxxxer/WindowsSandbox-ConfigsAndScripts#2]
This feature reduces user actions at the [Keystroke-level model](https://en.wikipedia.org/wiki/Keystroke-level_model). Users probably will open such folders manually.

Example: <Command>explorer.exe C:\Users\%USERNAME%\Downloads</Command>

**Comment by flexxxxer** [comment]
Sounds great. I will try to implement

**Comment by flexxxxer** [comment]
implemented by [ee4fd65](https://github.com/flexxxxer/WindowsSandbox-ConfigsAndScripts/commit/ee4fd650d174f0e899f1803425e5a5aaa15ecf7f) and [6109f70](https://github.com/flexxxxer/WindowsSandbox-ConfigsAndScripts/commit/6109f70c363acc029ab925e4eec085774e3788df).
